### ISSUE TITLE
Looks like a typo in the doc.

### ISSUE THREAD

**Issue by sarvghotra** [JockLawrie/SecureSessions.jl#2]
@JockLawrie The second last point of [Secure Cookies](https://github.com/JockLawrie/SecureSessions.jl/blob/master/docs/security_protocols.md#secure-cookies) has mentioned some encrypted_secret_key. Although I am not sure I think it should be encrypted_session_key.

**Comment by JockLawrie** [comment]
Nice catch. Thanks. Fixed.
